name: Cloudflare Pages Secrets
description: Set the Cloudflare Pages secrets
author: Nigel Williams-Lucas

branding:
  icon: 'upload-cloud'
  color: 'orange'

inputs:
  apiEmail:
    description: 'Your Cloudflare API Email'
    required: true
  apiToken:
    description: 'Your Cloudflare API Token'
    required: true
  accountId:
    description: 'Your Cloudflare Account ID'
    required: true
  quiet:
    description: 'Supresses output from Wrangler commands, defaults to `false`'
    required: false
    default: false
  projectName:
    description: 'The project name for the Cloudflare Pages'
    required: false
  wranglerConfigPath:
    description: 'The path to the wrangler.toml file'
    required: false
  createMissingProject:
    description: 'Create project if it does not exist'
    required: false
    default: false
  productionBranch:
    description: 'The production branch for the Cloudflare Pages'
    required: false
    default: 'main'
  secrets:
    description:
      'A string of environment variable names, separated by newlines. These will be bound to your
      Worker as Secrets and must match the names of environment variables declared in `env` of this
      workflow.'
    required: false

runs:
  using: 'node20'
  main: 'dist/index.mjs'
