name: Action Self-Test

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  self-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm run ci

      - name: Build
        run: npm run build

      - name: Check formatting
        run: npm run format

      - name: Run tests
        uses: ./
        env:
          FOO: 'foo'
          BAR: 'bar'
        with:
          apiToken: ${{ env.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ env.CLOUDFLARE_ACCOUNT_ID }}
          projectName: 'cloudflare-pages-secrets-test'
          secrets: |
            FOO
            BAR
