name: Action Self-Test

on:
  workflow_dispatch:

jobs:
  self-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm run build

      - name: Check formatting
        if: ${{ !env.ACT}}
        run: pnpm run format

      - name: Neither project name nor wrangler.toml path provided (this should fail)
        continue-on-error: true
        uses: ./
        env:
          ACT: ${{ env.ACT }}
        with:
          apiEmail: ${{ env.CLOUDFLARE_API_EMAIL }}
          apiToken: ${{ env.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ env.CLOUDFLARE_ACCOUNT_ID }}

      - name: Specify project name
        continue-on-error: true
        uses: ./
        env:
          ACT: ${{ env.ACT }}
        with:
          apiEmail: ${{ env.CLOUDFLARE_API_EMAIL }}
          apiToken: ${{ env.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ env.CLOUDFLARE_ACCOUNT_ID }}
          projectName: 'cloudflare-pages-secrets-test'

      - name: Specify project name with wrangler.toml
        continue-on-error: true
        uses: ./
        env:
          ACT: ${{ env.ACT }}
        with:
          apiEmail: ${{ env.CLOUDFLARE_API_EMAIL }}
          apiToken: ${{ env.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ env.CLOUDFLARE_ACCOUNT_ID }}
          wranglerConfigPath: 'test_data/wrangler-toml-for-project-name/wrangler.toml'

      - name: Specify project name and create missing project
        uses: ./
        env:
          ACT: ${{ env.ACT }}
        with:
          apiEmail: ${{ env.CLOUDFLARE_API_EMAIL }}
          apiToken: ${{ env.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ env.CLOUDFLARE_ACCOUNT_ID }}
          projectName: 'cloudflare-pages-secrets-test1'
          createProject: true

      - name:
          Specify project name and create missing project preferring projectName over wrangler.toml
        uses: ./
        env:
          ACT: ${{ env.ACT }}
        with:
          apiEmail: ${{ env.CLOUDFLARE_API_EMAIL }}
          apiToken: ${{ env.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ env.CLOUDFLARE_ACCOUNT_ID }}
          projectName: 'cloudflare-pages-secrets-test2'
          wranglerConfigPath: 'test_data/wrangler-toml-for-project-name/wrangler.toml'
          createProject: true

      - name: Specify project name and secrets
        continue-on-error: true
        uses: ./
        env:
          ACT: ${{ env.ACT }}
          FOO: 'foo'
          BAR: 'bar'
        with:
          apiEmail: ${{ env.CLOUDFLARE_API_EMAIL }}
          apiToken: ${{ env.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ env.CLOUDFLARE_ACCOUNT_ID }}
          projectName: 'cloudflare-pages-secrets-test3'
          createProject: true
          secrets: |
            FOO
            BAR

      - name: Specify project name and secrets with wrangler.toml containing variables as well
        continue-on-error: true
        uses: ./
        env:
          ACT: ${{ env.ACT }}
          FOO: 'foo'
          BAR: 'bar'
        with:
          apiEmail: ${{ env.CLOUDFLARE_API_EMAIL }}
          apiToken: ${{ env.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ env.CLOUDFLARE_ACCOUNT_ID }}
          projectName: 'cloudflare-pages-secrets-test4'
          createProject: true
          wranglerConfigPath: 'test_data/wrangler-toml-with-vars/wrangler.toml'
          vars: |
            FOO_VAR2=foo2
            BAR_VAR2=bar2
            BUZ_VAR=buz2
          secrets: |
            FOO
            BAR
